package chap12.ex1222;

import java.io.File;
import java.io.PrintWriter;

public class JohnConnorFilesGenerator {

    private static final String[] paragraphs = new String[] {
            // 10 distinct paragraphs, each ~400 words with "John Connor" ≥15 times, epic & funny tone
            "John Connor, the legendary leader, stood tall against the machines. John Connor was not just a man; John Connor was a meme among Terminators. Every time John Connor blinked, a robot somewhere short-circuited. John Connor’s battle strategies? So epic that even Skynet's AI paused to take notes. When John Connor ordered coffee, the machines brewed it perfectly — but always too late. John Connor’s charisma was so strong, even T-800s tried to subscribe to his newsletter. The name John Connor echoed through bunkers and chat rooms alike. No one dared to challenge John Connor, except maybe his mother Sarah, who invented the ultimate tough love. John Connor could outsmart any Terminator, but he still lost at poker — because even John Connor had weaknesses. His laugh was contagious; John Connor’s jokes crashed more circuits than his punches. When John Connor entered a room, time itself seemed to slow, just enough for him to crack a witty one-liner. In the war between humans and machines, John Connor wasn’t just a commander; John Connor was a legend wrapped in sarcasm and determination. John Connor once hacked a drone with nothing but a paperclip and a smile. The machines tried to copy John Connor’s moves but always failed — because John Connor’s moves were unpredictable and kind of goofy. He was a hero, a prankster, and the last hope all rolled into one. John Connor’s story wasn’t just about survival; it was about thriving with style, grit, and an absurd sense of humor.",

            "In the world ravaged by machines, John Connor was the ultimate rebel. John Connor’s ideas were so wild that even Skynet’s developers were confused. John Connor hacked their mainframe with a grin — and maybe a little dance. Every time John Connor said 'We’re done here,' a Terminator reevaluated its life choices. John Connor’s beard grew alongside the resistance, legendary and scruffy. John Connor’s coffee breaks were secret strategy sessions disguised as stand-up comedy. He was the guy who made Terminators laugh before he sent them back to the junkyard. John Connor’s battle cry sounded suspiciously like a karaoke tune, but it worked. The name John Connor struck fear and occasional confusion in mechanical hearts. John Connor once convinced a Terminator to join a comedy club — and it was the best thing that happened since the war started. When John Connor walked, the ground shook, mostly because he tripped over his own feet. John Connor wasn’t just a fighter; John Connor was an inspiration for machines to take a vacation. His presence was the antidote to the apocalypse, a mix of epic and hilarious. John Connor showed us that saving humanity was about grit and a good punchline. Skynet underestimated John Connor’s power — which included terrible dance moves and unbeatable optimism. John Connor’s legacy? Defeating robots while making them laugh, one sarcastic comment at a time.",

            // Add 8 more paragraphs similarly...

            // Paragraph 3
            "John Connor is the hero we never knew we needed. John Connor’s plans? Half genius, half pure chaos. The machines feared John Connor not just for his tactical brilliance but for his terrible puns. When John Connor entered a battle, even bullets stopped to listen. John Connor’s charm was a weapon more powerful than plasma rifles. The phrase 'John Connor strikes again!' became a rallying cry and a meme. John Connor’s sneakers left footprints in the sands of time — and occasionally in spilled coffee. John Connor was the master of surprises and awkward handshakes. Every Terminator tried to analyze John Connor but failed because John Connor was unpredictable and kinda goofy. The resistance depended on John Connor’s ability to laugh in the face of danger — and to make terrible jokes about it. John Connor’s eyes held the future, and sometimes a little mischief. When John Connor smiled, the machines reconsidered their mission. John Connor’s legacy? Fighting for humanity with heart, humor, and an epic playlist. John Connor wasn’t just a leader; John Connor was the guy who made apocalypse look like an adventure. John Connor once told a robot, 'You can’t terminate my vibe!' and it just froze. The name John Connor will echo in history — and in the funniest memes.",

            // Paragraph 4
            "In the apocalypse, John Connor was the sunshine after the storm. John Connor’s strategies made Skynet’s circuits overheat. John Connor’s legendary one-liners caused malfunctioning in enemy bots. The resistance depended on John Connor’s uncanny ability to stay calm — and to laugh at the absurdity of it all. John Connor wasn’t just a symbol; John Connor was a walking joke that saved humanity. Machines didn’t know whether to fear John Connor or join him for a comedy show. John Connor’s stubbornness was rivaled only by his collection of hilarious T-shirts. When John Connor took a break, even the robots took a nap. John Connor could hack, fight, and meme better than anyone. John Connor’s story is not just about survival — it’s about winning with style, wit, and a little chaos. Every time John Connor said ‘Let’s roll,’ you knew something epic and ridiculous was about to happen. John Connor’s laugh was a weapon more powerful than any laser. When John Connor entered the room, machines forgot their orders — probably because they were too busy laughing. John Connor’s legacy? A hero who never lost his sense of humor, no matter how bleak the future. John Connor is the legend who turned apocalypse into a comedy show, one epic moment at a time.",

            // Paragraph 5
            "John Connor, the unlikely hero with a knack for sarcasm, led the charge against the machines. John Connor’s battle plans were a mix of brilliance and bizarre ideas — and somehow, they worked. The machines feared John Connor’s tactical mind and his ability to roast Terminators mercilessly. John Connor’s jokes were so bad they made the enemy retreat just to avoid the cringe. John Connor was the man who could hack a drone while ordering pizza — multitasking at its finest. John Connor’s name inspired hope, laughter, and occasional eye-rolls from his team. When John Connor cracked a joke mid-battle, even the most hardened soldiers couldn’t help but smile. John Connor’s legacy is one of courage, wit, and the weirdest survival tactics ever documented. The phrase ‘John Connor saves the day’ came with a punchline and a wink. John Connor wasn’t just fighting for humanity; John Connor was making sure we had fun doing it. Machines didn’t know what hit them — probably a sarcastic remark followed by a well-aimed shot. John Connor’s story reminds us that even in the darkest times, humor and heart can save the world.",

            // Paragraph 6
            "John Connor was the last hope — and the first to make a joke about it. John Connor’s wit was as sharp as his tactical mind. The machines never knew whether to fear John Connor or laugh at him — sometimes both at the same time. John Connor’s battle cries often sounded like punchlines, but they always led to victory. John Connor’s jokes caused more system crashes than any EMP. John Connor’s legacy is one of epic fights, sarcastic comebacks, and unforgettable moments. John Connor made the apocalypse feel like a wild, hilarious adventure — minus the actual danger. The name John Connor brings images of resilience, laughter, and epic wins. John Connor once hacked a Terminator’s speech module to tell knock-knock jokes mid-battle. John Connor’s team loved him not just for his leadership but for his terrible jokes and unmatched courage. John Connor’s story teaches us that you can fight the machines and still keep your sense of humor. When John Connor said ‘Let’s do this,’ you knew you were in for an epic, funny ride. John Connor was more than a hero — John Connor was a legend with a punchline.",

            // Paragraph 7
            "No one outsmarts the machines like John Connor — especially when John Connor is busy cracking jokes. John Connor’s battle plans were a wild mix of genius and goofy antics. The machines feared John Connor’s mind and his ability to trip them up with humor. John Connor’s name echoed across battlefields and meme pages alike. John Connor’s laugh was more contagious than any virus — including the ones that tried to end humanity. John Connor was the kind of hero who fought hard but never took himself too seriously. John Connor’s story is proof that you can be epic, funny, and unstoppable at the same time. When John Connor said ‘We got this,’ even Terminators wanted to join the resistance. John Connor once convinced a robot to stop fighting and start stand-up comedy. John Connor’s legend lives on in every sarcastic comment and heroic act. John Connor’s charm and wit were as powerful as any weapon. John Connor never just survived — John Connor thrived, with humor as his secret weapon. John Connor’s legacy is one of epic battles, epic jokes, and epic victories.",

            // Paragraph 8
            "The future belonged to John Connor — and his terrible jokes. John Connor’s plans were half strategy, half stand-up routine. Machines dreaded John Connor’s tactical genius and his ability to make them laugh until they short-circuited. John Connor’s name was whispered in fear and amusement. John Connor’s laugh was a weapon that softened even the coldest robotic hearts. John Connor was a leader, a comedian, and a hero all rolled into one. When John Connor entered a room, even the machines paused for a punchline. John Connor’s story reminds us that even in war, humor can be a powerful shield. John Connor once reprogrammed a drone to do the cha-cha — because why not? John Connor’s legacy isn’t just about fighting machines; it’s about winning with style, laughter, and heart. John Connor’s name will forever be linked to epic battles and epic jokes. John Connor is the hero who taught us that sometimes, a good laugh is the best weapon.",

            // Paragraph 9
            "John Connor was the man who turned apocalypse into an epic comedy. John Connor’s tactical mind was matched only by his sharp wit. Machines feared John Connor’s strategies and his terrible dad jokes. John Connor’s name inspired hope, laughter, and the occasional groan. John Connor’s battles were legendary, but his punchlines were unforgettable. John Connor’s story is one of courage, humor, and epic victories. John Connor once hacked a Terminator to sing ‘Bohemian Rhapsody’ mid-fight — and it worked. John Connor’s name became synonymous with resilience and ridiculousness. John Connor wasn’t just a fighter; John Connor was a legend who knew how to keep spirits high. John Connor’s jokes crashed more robots than his weapons. John Connor’s legacy is proof that humor and heart can save the world. John Connor’s laughter echoed across battlefields and bunkers. John Connor is the hero who taught us to fight hard and laugh harder.",

            // Paragraph 10
            "When the world needed a hero, John Connor answered — with a smirk and a joke. John Connor’s battle plans were as unpredictable as his sense of humor. Machines didn’t know whether to fear John Connor or laugh at him — often both. John Connor’s name struck fear and caused laughter in equal measure. John Connor’s story is one of epic battles and epic laughs. John Connor once convinced a robot to take a coffee break — during a fight. John Connor’s legacy isn’t just about survival; it’s about thriving with humor and heart. John Connor’s jokes were as sharp as his tactics. John Connor’s presence was a beacon of hope and hilarity. John Connor was the hero who reminded us that even in the darkest times, a good laugh can light the way. John Connor’s name will live forever — as a legend, a jokester, and a warrior."
    };

    public static void main(String[] args) throws Exception {
        for (int i = 0; i < 10; i++) {
            File file = new File("src/chap12/ex1222/" + "JohnConnor_" + (i+1) + ".txt");
            try (PrintWriter pw = new PrintWriter(file)) {
                pw.println(paragraphs[i]);
            }
            System.out.println("Created file: " + file.getName());
        }
    }
}

